default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        language_version: python3
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: package-lock.json|_vendor/.*|docs/styles/.*
  # ty type checker (replacing mypy) - https://astral.sh/blog/ty
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.17
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: check-ui-v2
        name: Check UI v2
        language: system
        entry: sh
        args:
          [
            "-c",
            ". $NVM_DIR/nvm.sh || true && cd ui-v2 && nvm use || true && npm i --no-upgrade --silent --no-progress && npm run check:staged",
          ]
        files: |
          (?x)^(
              .pre-commit-config.yaml|
              ui-v2/.*
          )$
        pass_filenames: false
      - id: service-sync-ui-v2-openapi
        name: Sync UI v2 OpenAPI
        language: system
        entry: sh
        args:
          [
            "-c",
            ". $NVM_DIR/nvm.sh || true && cd ui-v2 && nvm use || true && npm i --no-upgrade --silent --no-progress && npm run service-sync",
          ]
        files: |
          (?x)^(
              .pre-commit-config.yaml|
              .pre-commit-config.yaml|
              src/prefect/server/api/.*|
              src/prefect/server/schemas/.*|
              src/prefect/server/events/.*|
              src/prefect/server/utilities/schemas/.*|
              ui-v2/package.json
          )$
        pass_filenames: false
        stages:
          - pre-push
