name: prefect
channels:
    - conda-forge
dependencies:
    - black
    - click
    - croniter
    - cryptography
    - distributed
    - graphviz
    - ipdb
    - ipython
    - jsonpickle
    - jupyter
    - mypy
    - mypy_extensions
    - pip:
        - pytest-cov
        - tox
        - typing_extensions
    - pylint
    - pytest
    - pytest-env
    - pytest-xdist
    - python>=3.4
    - python-dateutil
    - requests
    - toml
    - typing
    - wrapt
