apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-job-UUID
  labels:
    app: prefect-job-UUID
    identifier: UUID
spec:
  template:
    metadata:
      labels:
        app: prefect-job-UUID
        identifier: UUID
    spec:
      containers:
        - name: flow
          image: prefecthq/prefect:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["prefect execute cloud-flow"]
          env:
            - name: PREFECT__CLOUD__API
              value: PREFECT__CLOUD__API
            - name: PREFECT__CLOUD__AUTH_TOKEN
              value: PREFECT__CLOUD__AUTH_TOKEN
            - name: PREFECT__CONTEXT__FLOW_RUN_ID
              value: PREFECT__CONTEXT__FLOW_RUN_ID
            - name: PREFECT__CONTEXT__FLOW_ID
              value: PREFECT__CONTEXT__FLOW_ID
            - name: PREFECT__CONTEXT__NAMESPACE
              value: PREFECT__CONTEXT__NAMESPACE
            - name: PREFECT__CLOUD__AGENT__LABELS
              value: PREFECT__CLOUD__AGENT__LABELS
            - name: PREFECT__LOGGING__LOG_TO_CLOUD
              value: PREFECT__LOGGING__LOG_TO_CLOUD
            - name: PREFECT__CLOUD__USE_LOCAL_SECRETS
              value: "false"
            - name: PREFECT__LOGGING__LEVEL
              value: "DEBUG"
            - name: PREFECT__ENGINE__FLOW_RUNNER__DEFAULT_CLASS
              value: "prefect.engine.cloud.CloudFlowRunner"
            - name: PREFECT__ENGINE__TASK_RUNNER__DEFAULT_CLASS
              value: "prefect.engine.cloud.CloudTaskRunner"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
      restartPolicy: Never
      imagePullSecrets:
      - name: ""
