blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Read the documentation
    url: https://docs.prefect.io/
    about: Please consult the documentation before opening any issues!
  - name: ðŸ™‹ Ask a question
    url: https://discourse.prefect.io/c/21
    about: Ask questions about how to use Prefect on our Discourse forum.
  - name: ðŸ’¬ Chat with experts
    url: https://www.prefect.io/slack
    about: Join thousands of Prefect experts, engineers, and users in our Slack community
  - name: ðŸ¦† Book a rubber duck
    url: https://calendly.com/prefect-experts/rubber-duck
    about: Book time with a Prefect engineer!
  - name: ðŸ”’ Report a security issue
    url: https://www.prefect.io/security/bug-bounty-program/
    about: Responsibly disclose a potential security issue.
