kind: Pod
metadata:
  labels:
    app: prefect-dask-worker
spec:
  restartPolicy: Never
  containers:
  - image: gcr.io/prefect-dev/prefect
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --no-bokeh, --death-timeout, '600']
    name: dask-worker
    env:
      - name: PREFECT__CLOUD__GRAPHQL
        value: $PREFECT__CLOUD__GRAPHQL
      - name: PREFECT__CLOUD__LOG
        value: PREFECT__CLOUD__LOG
      - name: PREFECT__CLOUD__RESULT_HANDLER
        value: PREFECT__CLOUD__RESULT_HANDLER
      - name: PREFECT__CLOUD__AUTH_TOKEN
        value: PREFECT__CLOUD__AUTH_TOKEN
      - name: PREFECT__CONTEXT__FLOW_RUN_ID
        value: PREFECT__CONTEXT__FLOW_RUN_ID
      - name: PREFECT__CLOUD__USE_LOCAL_SECRETS
        value: "false"
      - name: PREFECT__ENGINE__FLOW_RUNNER__DEFAULT_CLASS
        value: "prefect.engine.cloud.CloudFlowRunner"
      - name: PREFECT__ENGINE__TASK_RUNNER__DEFAULT_CLASS
        value: "prefect.engine.cloud.CloudTaskRunner"
      - name: PREFECT__ENGINE__EXECUTOR__DEFAULT_CLASS
        value: "prefect.engine.executors.DaskExecutor"
      - name: PREFECT__LOGGING__LOG_TO_CLOUD
        value: "true"
      - name: PREFECT__LOGGING__LEVEL
        value: "DEBUG"
      - name: PREFECT__DEBUG
        value: "true"
      - name: EXTRA_PIP_PACKAGES
        value: fastparquet
