extends: spelling
message: "Did you really mean '%s'?"
level: error
# This disables the built-in filters. If you omit this
# key or set it to false, custom filters (see below) are
# added on top of the built-in ones.
#
# By default, filters for acronyms, abbreviations, and
# numbers are included.
custom: true
# A "filter" is a regular expression specifying words
# to ignore during spell checking.
filters:
    # Ignore all words starting with 'py'.
    #
    # e.g., 'PyYAML'.
    - '[_].*\b'
    - "my_worker_module"
