name: Release orion-design

on:
  workflow_dispatch:
  push:
    paths: 
      - orion-ui/packages/orion-design/package.json
    branches:
      - main

jobs:
  version-change-check:
    name: Check package version
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
        with: 
          persist-credentials: false

      - uses: EndBug/version-check@v2.1.0
        id: check
        with: 
          diff-search: true
          file-name: ./orion-ui/packages/orion-design/package.json

      - uses: andymckay/cancel-action@0.2
        if: steps.check.outputs.changed == 'false'
        
  build-and-publish:
    name: Build and publish release
    runs-on: ubuntu-latest
    needs: [version-change-check]
    environment: 'npm'

    steps:
      - uses: actions/checkout@v2

      - name: Read version from .nvmrc
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
        id: nvm

      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NODE_VERSION }}"
    
      - name: Install orion-ui dependencies
        working-directory: ./orion-ui
        run: npm ci install
      
      - name: Install orion-design dependencies
        working-directory: ./orion-ui/packages/orion-design
        run: npm ci install
      
      - name: Build project
        working-directory: ./orion-ui/packages/orion-design
        run: npm run build

      - name: Get package version
        uses: EndBug/version-check@v2.1.0
        id: version
        with: 
          diff-search: true
          file-name: ./orion-ui/packages/orion-design/package.json

      - name: Publish package
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: public
          package: ./orion-ui/packages/orion-design/package.json