name: Test Orion Design

on: [pull_request]

jobs:

  test-build:
    name: Build & Test Release
    runs-on: ubuntu-latest
    environment: 'npm'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      
      - name: Install orion-ui dependencies
        working-directory: ./orion-ui
        run: npm ci install
      
      - name: Install orion-design dependencies
        working-directory: ./orion-ui/packages/orion-design
        run: npm ci install
      
      - name: Build project
        working-directory: ./orion-ui/packages/orion-design
        run: npm run build
